language: node_js
node_js:
  - '6'
install:
  - npm install -g npm
  - npm install -g node-gyp
  - npm install -g typings
  - typings install
  - npm install
script: npm run compile
# after_success: npm run converalls
